### ISSUE TITLE
多网卡多IP服务器时要怎么配置ListenIP

### ISSUE THREAD

**Issue by custompal** [yangjiechina/gsip#1]
大佬，如果是多网卡多IP服务器时要怎么配置ListenIP啊？配置成"0.0.0.0“的话，sip信令里的via以及contact里的ip就变成"0.0.0.0“了

**Comment by custompal** [comment]
还是server的配置要改成json数组形式，然后针对每个ListenIP创建一个服务来监听？

**Comment by ydajiang** [comment]
> 还是server的配置要改成json数组形式，然后针对每个ListenIP创建一个服务来监听？

等会加一个设置全局Contact的函数。多网卡进出口 是一个IP吗？

**Comment by custompal** [comment]
不是，两个ip还是不同网段的，我觉得弄成全局Contact也不好

**Comment by custompal** [comment]
应该针对每个设备，它是通过哪个网卡注册进来就用那个网卡ip

**Comment by custompal** [comment]
我尝试改了点代码，保存设备注册上来时携带的requesturi里的服务器IP地址作为每次发送请求的sendby，要不我提个pr供你参考下？

**Comment by custompal** [comment]
requesturi里的服务器地址感觉又不靠谱，万一设备程序写的有问题，那就坑了，开始想的是通过conn来获取本地ip地址作为sendby，但是如果是公网服务器，获取到的本地地址是内网的而不是公网地址，所以还是用的requesturi里的服务器地址

**Comment by ydajiang** [comment]
> requesturi里的服务器地址感觉又不靠谱，万一设备程序写的有问题，那就坑了，开始想的是通过conn来获取本地ip地址作为sendby，但是如果是公网服务器，获取到的本地地址是内网的而不是公网地址，所以还是用的requesturi里的服务器地址

是的，用 request uri不可靠。很多设备，比如海康就填的域。

**Comment by custompal** [comment]
那咋搞呢

**Comment by ydajiang** [comment]
用2个ListeningPort 分别监听不同网卡的 ip和端口。UDP发送响应是用的设备请求的conn，发送请求也是用的listeningPort的 conn。tcp dlient 可能会有问题，直接dail的server地址，不确定用的哪个网卡。




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月23日(周五) 下午4:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yangjiechina/gsip] 多网卡多IP服务器时要怎么配置ListenIP (Issue #1)




 
那咋搞呢

**Comment by ydajiang** [comment]
如果监听0.0.0.0 不同网卡ip注册上来的设备可以正常通信。那就监听0.0.0.0就行了，via里面的sendby 无关紧要。给每个listeningport 设置一个contact就行了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月23日(周五) 下午4:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yangjiechina/gsip] 多网卡多IP服务器时要怎么配置ListenIP (Issue #1)




 
那咋搞呢

**Comment by custompal** [comment]
> 如果监听0.0.0.0 不同网卡ip注册上来的设备可以正常通信。那就监听0.0.0.0就行了，via里面的sendby 无关紧要。给每个listeningport 设置一个contact就行了。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年9月23日(周五) 下午4:18 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [yangjiechina/gsip] 多网卡多IP服务器时要怎么配置ListenIP (Issue #1) 那咋搞呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

监听0.0.0.0是可以正常通信的，具体改还是大佬你来把控吧，小弟我才刚学几天的go。。

**Comment by ydajiang** [comment]
> > 如果监听0.0.0.0 不同网卡ip注册上来的设备可以正常通信。那就监听0.0.0.0就行了，via里面的sendby 无关紧要。给每个listeningport 设置一个contact就行了。
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2022年9月23日(周五) 下午4:18 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [yangjiechina/gsip] 多网卡多IP服务器时要怎么配置ListenIP (Issue #1) 那咋搞呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 监听0.0.0.0是可以正常通信的，具体改还是大佬你来把控吧，小弟我才刚学几天的go。。

用上面那个方法好一点。直接0.0.0.0 不太好判断是哪个网卡收的包。晚上我会改下代码。

**Comment by custompal** [comment]
好的，大佬

**Comment by ydajiang** [comment]
拉取下最新的代码，参考examples server，把127.0.0.1 改成另外一个网卡IP

**Comment by custompal** [comment]
好的，我今天测一下

**Comment by custompal** [comment]
大佬，生成请求消息时cseq num写死的1，但是有些请求例如invite请求cseq num是有用的，可以用来判断是否为reinvite，写死就有问题了
![image](https://user-images.githubusercontent.com/50011641/192429011-9669e8b7-710a-457b-a55f-317d52948a8e.png)

**Comment by ydajiang** [comment]
> 大佬，生成请求消息时cseq num写死的1，但是有些请求例如invite请求cseq num是有用的，可以用来判断是否为reinvite，写死就有问题了 ![image](https://user-images.githubusercontent.com/50011641/192429011-9669e8b7-710a-457b-a55f-317d52948a8e.png)

首次发送消息为1。后面涉及到dialog的，用dialog createRequest。

**Comment by custompal** [comment]
哦哦，原来如此，是我源码看得不够细致，哈哈

**Comment by custompal** [comment]
大佬，双网卡测试ok，暂时没什么问题，我先关了issue吧
