### ISSUE TITLE
如何兼容一些回复subscribe消息里面没有带Contact的设备

### ISSUE THREAD

**Issue by custompal** [yangjiechina/gsip#2]
我测试过程中发现有些设备回复subscribe消息里没有Contact字段，会导致Response检查头失败，这种设备怎么兼容好呢
![image](https://user-images.githubusercontent.com/50011641/194737731-b06fdaf6-b0b1-4da1-be43-31448cd49158.png)
![image](https://user-images.githubusercontent.com/50011641/194737899-6b9cc1de-43e9-487d-9f05-c7f30b328872.png)

**Comment by ydajiang** [comment]
> 我测试过程中发现有些设备回复subscribe消息里没有Contact字段，会导致Response检查头失败，这种设备怎么兼容好呢 ![image](https://user-images.githubusercontent.com/50011641/194737731-b06fdaf6-b0b1-4da1-be43-31448cd49158.png) ![image](https://user-images.githubusercontent.com/50011641/194737899-6b9cc1de-43e9-487d-9f05-c7f30b328872.png)

自己创建一个Contact.用deviceID和conn地址

**Comment by custompal** [comment]
如果服务器在公网，设备在内网，那么conn地址是设备的公网地址吧，这样会有问题吗

**Comment by ydajiang** [comment]
> 如果服务器在公网，设备在内网，那么conn地址是设备的公网地址吧，这样会有问题吗
这不是问题。只要在内网的设备，能和公网的服务器主动通信就行。 简单点说，内网的设备只要能上广域网网就行。设备的内网地址，会经过路由NAT 变为公网地址。服务器也是向这个nat地址发包的。如果向内网地址发，怎么发得过去？

**Comment by custompal** [comment]
哈哈，我就是不太确定所以跟大佬确定一下。。现在我改了一下，parseMessage加了conn参数，然后加了下面这段代码，让msg.CheckHeaders()能通过
![image](https://user-images.githubusercontent.com/50011641/194792235-8586484c-a5f5-426e-8ff3-1dcb37c37797.png)
